# Generated by Django 5.2.17 on 2026-08-13 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertyValuationEntity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area_m2', models.FloatField(help_text='Área total en metros cuadrados')),
                ('bedrooms', models.IntegerField(help_text='Número de dormitorios')),
                ('bathrooms', models.IntegerField(help_text='Número de baños')),
                ('parking_spaces', models.IntegerField(default=0, help_text='Número de estacionamientos / cocheras')),
                ('age_years', models.IntegerField(default=0, help_text='Antigüedad del inmueble en años')),
                ('district', models.CharField(choices=[('Miraflores', 'Miraflores'), ('San Isidro', 'San Isidro'), ('Santiago de Surco', 'Santiago de Surco'), ('San Borja', 'San Borja'), ('La Molina', 'La Molina'), ('Barranco', 'Barranco'), ('Jesús María', 'Jesús María'), ('Magdalena del Mar', 'Magdalena del Mar'), ('Lince', 'Lince'), ('Pueblo Libre', 'Pueblo Libre'), ('San Miguel', 'San Miguel'), ('Surquillo', 'Surquillo'), ('Chorrillos', 'Chorrillos'), ('San Martín de Porres', 'San Martín de Porres'), ('Ate', 'Ate'), ('Breña', 'Breña'), ('San Juan de Lurigancho', 'San Juan de Lurigancho'), ('San Juan de Miraflores', 'San Juan de Miraflores'), ('La Victoria', 'La Victoria'), ('Rímac', 'Rímac'), ('Santa Anita', 'Santa Anita'), ('Villa El Salvador', 'Villa El Salvador'), ('Villa María del Triunfo', 'Villa María del Triunfo'), ('Comas', 'Comas'), ('Carabayllo', 'Carabayllo'), ('Independencia', 'Independencia'), ('Los Olivos', 'Los Olivos'), ('Puente Piedra', 'Puente Piedra'), ('Lurín', 'Lurín'), ('Pachacámac', 'Pachacámac'), ('San Bartolo', 'San Bartolo'), ('Punta Hermosa', 'Punta Hermosa'), ('Callao', 'Callao'), ('Bellavista', 'Bellavista'), ('La Perla', 'La Perla'), ('La Punta', 'La Punta'), ('Otro', 'Otro')], help_text='Distrito exacto de ubicación', max_length=50)),
                ('estimated_price_usd', models.FloatField(blank=True, help_text='Precio estimado comercial en USD generado por el modelo ML', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Property Valuation',
                'verbose_name_plural': 'Property Valuations',
                'db_table': 'property_valuations',
            },
        ),
    ]
