from django.db import models


class DistrictEnum(models.TextChoices):
    MIRAFLORES = 'Miraflores', 'Miraflores'
    SAN_ISIDRO = 'San Isidro', 'San Isidro'
    SANTIAGO_DE_SURCO = 'Santiago de Surco', 'Santiago de Surco'
    SAN_BORJA = 'San Borja', 'San Borja'
    LA_MOLINA = 'La Molina', 'La Molina'
    BARRANCO = 'Barranco', 'Barranco'
    JESUS_MARIA = 'Jesús María', 'Jesús María'
    MAGDALENA_DEL_MAR = 'Magdalena del Mar', 'Magdalena del Mar'
    LINCE = 'Lince', 'Lince'
    PUEBLO_LIBRE = 'Pueblo Libre', 'Pueblo Libre'
    SAN_MIGUEL = 'San Miguel', 'San Miguel'
    SURQUILLO = 'Surquillo', 'Surquillo'
    CHORRILLOS = 'Chorrillos', 'Chorrillos'
    SAN_MARTIN_DE_PORRES = 'San Martín de Porres', 'San Martín de Porres'
    ATE = 'Ate', 'Ate'
    BRENA = 'Breña', 'Breña'
    SAN_JUAN_DE_LURIGANCHO = 'San Juan de Lurigancho', 'San Juan de Lurigancho'
    SAN_JUAN_DE_MIRAFLORES = 'San Juan de Miraflores', 'San Juan de Miraflores'
    LA_VICTORIA = 'La Victoria', 'La Victoria'
    RIMAC = 'Rímac', 'Rímac'
    SANTA_ANITA = 'Santa Anita', 'Santa Anita'
    VILLA_EL_SALVADOR = 'Villa El Salvador', 'Villa El Salvador'
    VILLA_MARIA_DEL_TRIUNFO = 'Villa María del Triunfo', 'Villa María del Triunfo'
    COMAS = 'Comas', 'Comas'
    CARABAYLLO = 'Carabayllo', 'Carabayllo'
    INDEPENDENCIA = 'Independencia', 'Independencia'
    LOS_OLIVOS = 'Los Olivos', 'Los Olivos'
    PUENTE_PIEDRA = 'Puente Piedra', 'Puente Piedra'
    LURIN = 'Lurín', 'Lurín'
    PACHACAMAC = 'Pachacámac', 'Pachacámac'
    SAN_BARTOLO = 'San Bartolo', 'San Bartolo'
    PUNTA_HERMOSA = 'Punta Hermosa', 'Punta Hermosa'
    CALLAO = 'Callao', 'Callao'
    BELLAVISTA = 'Bellavista', 'Bellavista'
    LA_PERLA = 'La Perla', 'La Perla'
    LA_PUNTA = 'La Punta', 'La Punta'
    OTRO = 'Otro', 'Otro'